In [1]:
from __future__ import print_function
import torch

In [2]:
u = torch.empty(4,2)

In [3]:
u

tensor([[-9.7844e+35,  4.5773e-41],
        [-9.7844e+35,  4.5773e-41],
        [ 6.3370e+31,  3.0878e-41],
        [ 6.3370e+31,  3.0878e-41]])

In [9]:
x = torch.randn(4,4)
x

tensor([[-0.6927,  0.4721, -1.6180, -0.5113],
        [-1.0127,  1.2162,  1.2056,  1.0050],
        [ 0.7786,  0.2275, -1.1425, -0.0134],
        [-0.6774, -0.1093,  0.4685, -1.1443]])

In [10]:
y = x.view(16) # convert from matrix to vector  
y

tensor([-0.6927,  0.4721, -1.6180, -0.5113, -1.0127,  1.2162,  1.2056,  1.0050,
         0.7786,  0.2275, -1.1425, -0.0134, -0.6774, -0.1093,  0.4685, -1.1443])

In [11]:
y.shape

torch.Size([16])

In [12]:
z = x.view(-1,8)
z

tensor([[-0.6927,  0.4721, -1.6180, -0.5113, -1.0127,  1.2162,  1.2056,  1.0050],
        [ 0.7786,  0.2275, -1.1425, -0.0134, -0.6774, -0.1093,  0.4685, -1.1443]])

In [13]:
z.shape

torch.Size([2, 8])

In [14]:
x

tensor([[-0.6927,  0.4721, -1.6180, -0.5113],
        [-1.0127,  1.2162,  1.2056,  1.0050],
        [ 0.7786,  0.2275, -1.1425, -0.0134],
        [-0.6774, -0.1093,  0.4685, -1.1443]])

In [16]:
x.view(1,-1).shape

torch.Size([1, 16])